SELECT p.GENDER, AVG(DATEDIFF(YEAR, TRY_CONVERT(DATE, p.BIRTHDATE), GETDATE())) AS Average_Age,
COUNT(*) AS Number_PAtients FROM patients AS p JOIN conditions c ON p.Id = c.PATIENT
WHERE c.DESCRIPTION LIKE '%anemia%' GROUP BY p.GENDER;