SELECT e.PATIENT, COUNT(DISTINCT e.Id) AS Number_Visits, RANK() OVER
(ORDER BY COUNT(DISTINCT e.Id) DESC) AS Rang FROM encounters AS e WHERE e.PATIENT IN
(SELECT DISTINCT PATIENT FROM conditions WHERE DESCRIPTION LIKE '%anemia%') GROUP BY e.PATIENT;